export {
  DurationInMs,
  DurationInSeconds,
  HermesConnection,
  HermesConnectionConfig,
  HexString,
  UnixTimestamp,
  AssetType,
  BinaryPriceUpdate,
  EncodingType,
  GetVaaCcipInput,
  GetVaaCcipResponse,
  GetVaaResponse,
  ParsedPriceUpdate,
  PriceFeedMetadata,
  PriceIdInput,
  PriceUpdate,
} from "./HermesConnection";
