# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orderbook.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'orderbook.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0forderbook.proto\x12\x0bhyperliquid\"{\n\rL2BookRequest\x12\x0c\n\x04\x63oin\x18\x01 \x01(\t\x12\x10\n\x08n_levels\x18\x02 \x01(\r\x12\x17\n\nn_sig_figs\x18\x03 \x01(\rH\x00\x88\x01\x01\x12\x15\n\x08mantissa\x18\x04 \x01(\x04H\x01\x88\x01\x01\x42\r\n\x0b_n_sig_figsB\x0b\n\t_mantissa\"\x88\x01\n\x0cL2BookUpdate\x12\x0c\n\x04\x63oin\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\x04\x12\x14\n\x0c\x62lock_number\x18\x03 \x01(\x04\x12\"\n\x04\x62ids\x18\x04 \x03(\x0b\x32\x14.hyperliquid.L2Level\x12\"\n\x04\x61sks\x18\x05 \x03(\x0b\x32\x14.hyperliquid.L2Level\",\n\x07L2Level\x12\n\n\x02px\x18\x01 \x01(\t\x12\n\n\x02sz\x18\x02 \x01(\t\x12\t\n\x01n\x18\x03 \x01(\r2]\n\x12OrderBookStreaming\x12G\n\x0cStreamL2Book\x12\x1a.hyperliquid.L2BookRequest\x1a\x19.hyperliquid.L2BookUpdate0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orderbook_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_L2BOOKREQUEST']._serialized_start=32
  _globals['_L2BOOKREQUEST']._serialized_end=155
  _globals['_L2BOOKUPDATE']._serialized_start=158
  _globals['_L2BOOKUPDATE']._serialized_end=294
  _globals['_L2LEVEL']._serialized_start=296
  _globals['_L2LEVEL']._serialized_end=340
  _globals['_ORDERBOOKSTREAMING']._serialized_start=342
  _globals['_ORDERBOOKSTREAMING']._serialized_end=435
# @@protoc_insertion_point(module_scope)
