FROM node:18.19.1-slim@sha256:246bf34b0c7cf8d9ff7cbe0c1ff44b178051f06c432c8e7df1645f1bd20b0352 as builder-base
WORKDIR /usr/src/pyth
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN apt-get update && apt-get install -y git python3 make gcc g++ && corepack enable
COPY ./ .
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile


FROM node:18.19.1-alpine@sha256:c7620fdecfefb96813da62519897808775230386f4c8482e972e37b8b18cb460 as runner-base
WORKDIR /srv
ENV NODE_ENV production
RUN addgroup --system --gid 1001 pyth && adduser --system --uid 1001 pyth -g pyth && chown pyth:pyth .
USER pyth


FROM builder-base AS builder
ARG package
RUN pnpm exec lerna run build --scope="$package" --include-dependencies
RUN pnpm deploy --filter $package --prod /srv/$package


FROM runner-base AS runner
ARG package
COPY --from=builder --chown=pyth:pyth /srv/${package} ./
CMD [ "npm", "start" ]
