/*
 * hermes
 *
 * Hermes is an agent that provides Verified Prices from the Pythnet Pyth Oracle.
 *
 * The version of the OpenAPI document: 0.8.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AssetType {
    #[serde(rename = "crypto")]
    Crypto,
    #[serde(rename = "fx")]
    Fx,
    #[serde(rename = "equity")]
    Equity,
    #[serde(rename = "metal")]
    Metal,
    #[serde(rename = "rates")]
    Rates,
    #[serde(rename = "crypto_redemption_rate")]
    CryptoRedemptionRate,

}

impl std::fmt::Display for AssetType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Crypto => write!(f, "crypto"),
            Self::Fx => write!(f, "fx"),
            Self::Equity => write!(f, "equity"),
            Self::Metal => write!(f, "metal"),
            Self::Rates => write!(f, "rates"),
            Self::CryptoRedemptionRate => write!(f, "crypto_redemption_rate"),
        }
    }
}

impl Default for AssetType {
    fn default() -> AssetType {
        Self::Crypto
    }
}

