/*
 * hermes
 *
 * Hermes is an agent that provides Verified Prices from the Pythnet Pyth Oracle.
 *
 * The version of the OpenAPI document: 0.8.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BinaryUpdate {
    #[serde(rename = "data")]
    pub data: Vec<String>,
    #[serde(rename = "encoding")]
    pub encoding: models::EncodingType,
}

impl BinaryUpdate {
    pub fn new(data: Vec<String>, encoding: models::EncodingType) -> BinaryUpdate {
        BinaryUpdate {
            data,
            encoding,
        }
    }
}

