/*
 * hermes
 *
 * Hermes is an agent that provides Verified Prices from the Pythnet Pyth Oracle.
 *
 * The version of the OpenAPI document: 0.8.6
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetVaaCcipResponse {
    #[serde(rename = "data")]
    pub data: String,
}

impl GetVaaCcipResponse {
    pub fn new(data: String) -> GetVaaCcipResponse {
        GetVaaCcipResponse { data }
    }
}
