/*
 * hermes
 *
 * Hermes is an agent that provides Verified Prices from the Pythnet Pyth Oracle.
 *
 * The version of the OpenAPI document: 0.8.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetVaaResponse {
    #[serde(rename = "publishTime")]
    pub publish_time: i64,
    /// The VAA binary represented as a base64 string.
    #[serde(rename = "vaa")]
    pub vaa: String,
}

impl GetVaaResponse {
    pub fn new(publish_time: i64, vaa: String) -> GetVaaResponse {
        GetVaaResponse {
            publish_time,
            vaa,
        }
    }
}

