/*
 * hermes
 *
 * Hermes is an agent that provides Verified Prices from the Pythnet Pyth Oracle.
 *
 * The version of the OpenAPI document: 0.8.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ParsedPublisherStakeCapsUpdate {
    #[serde(rename = "publisher_stake_caps")]
    pub publisher_stake_caps: Vec<models::ParsedPublisherStakeCap>,
}

impl ParsedPublisherStakeCapsUpdate {
    pub fn new(publisher_stake_caps: Vec<models::ParsedPublisherStakeCap>) -> ParsedPublisherStakeCapsUpdate {
        ParsedPublisherStakeCapsUpdate {
            publisher_stake_caps,
        }
    }
}

