/*
 * hermes
 *
 * Hermes is an agent that provides Verified Prices from the Pythnet Pyth Oracle.
 *
 * The version of the OpenAPI document: 0.8.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ParsedPublisherStakeCap {
    #[serde(rename = "cap")]
    pub cap: i64,
    #[serde(rename = "publisher")]
    pub publisher: String,
}

impl ParsedPublisherStakeCap {
    pub fn new(cap: i64, publisher: String) -> ParsedPublisherStakeCap {
        ParsedPublisherStakeCap {
            cap,
            publisher,
        }
    }
}

