/*
 * hermes
 *
 * Hermes is an agent that provides Verified Prices from the Pythnet Pyth Oracle.
 *
 * The version of the OpenAPI document: 0.8.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PriceFeedMetadata {
    #[serde(rename = "attributes")]
    pub attributes: std::collections::HashMap<String, String>,
    #[serde(rename = "id")]
    pub id: String,
}

impl PriceFeedMetadata {
    pub fn new(attributes: std::collections::HashMap<String, String>, id: String) -> PriceFeedMetadata {
        PriceFeedMetadata {
            attributes,
            id,
        }
    }
}

