/*
 * hermes
 *
 * Hermes is an agent that provides Verified Prices from the Pythnet Pyth Oracle.
 *
 * The version of the OpenAPI document: 0.8.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PriceUpdate {
    #[serde(rename = "binary")]
    pub binary: Box<models::BinaryUpdate>,
    #[serde(rename = "parsed", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub parsed: Option<Option<Vec<models::ParsedPriceUpdate>>>,
}

impl PriceUpdate {
    pub fn new(binary: models::BinaryUpdate) -> PriceUpdate {
        PriceUpdate {
            binary: Box::new(binary),
            parsed: None,
        }
    }
}

