/*
 * hermes
 *
 * Hermes is an agent that provides Verified Prices from the Pythnet Pyth Oracle.
 *
 * The version of the OpenAPI document: 0.8.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcPriceFeedMetadataV2 {
    #[serde(rename = "prev_publish_time", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub prev_publish_time: Option<Option<i64>>,
    #[serde(rename = "proof_available_time", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub proof_available_time: Option<Option<i64>>,
    #[serde(rename = "slot", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub slot: Option<Option<i64>>,
}

impl RpcPriceFeedMetadataV2 {
    pub fn new() -> RpcPriceFeedMetadataV2 {
        RpcPriceFeedMetadataV2 {
            prev_publish_time: None,
            proof_available_time: None,
            slot: None,
        }
    }
}

