/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.89.2
  Forc version: 0.60.0
  Fuel-Core version: 0.27.0
*/

export type { PythContractAbi } from "./PythContractAbi";

export { PythContractAbi__factory } from "./factories/PythContractAbi__factory";
