/**
 * Change Log Data Generator
 *
 * Bundles the daily diff JSONs in `data/changelog-diffs/` into
 * `src/components/ChangeLog/generated-data.ts`, the typed module the
 * `<ChangeLog />` component reads at build time.
 *
 * Diffs themselves are produced by `scripts/snapshot-and-diff.ts`,
 * which runs daily from `.github/workflows/changelog-snapshot.yml`.
 * This script does no diffing — it only stitches the last
 * `DAYS_TO_RENDER` diff files into a `ChangeLog` shape.
 *
 * Usage:
 *
 *   pnpm generate:changelog
 */

/* eslint-disable no-console */

import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import type { Day, DaySummary } from "./changelog-lib";

const HERE = dirname(fileURLToPath(import.meta.url));
const DIFFS_DIR = resolve(HERE, "../data/changelog-diffs");
const OUTPUT_FILE = resolve(
  HERE,
  "../src/components/ChangeLog/generated-data.ts",
);
const DAYS_TO_RENDER = 15;

const isoFromFilename = (f: string): string | undefined =>
  /^\d{4}-\d{2}-\d{2}\.json$/.test(f) ? f.replace(/\.json$/, "") : undefined;

const main = (): void => {
  if (!existsSync(DIFFS_DIR)) {
    mkdirSync(DIFFS_DIR, { recursive: true });
  }

  const filenames = readdirSync(DIFFS_DIR)
    .map((f) => isoFromFilename(f))
    .filter((d): d is string => d !== undefined)
    .sort();

  const recent = filenames.slice(-DAYS_TO_RENDER);

  const days: Day[] = recent.map((date) =>
    JSON.parse(
      readFileSync(resolve(DIFFS_DIR, `${date}.json`), "utf8"),
    ) as Day,
  );

  const totals: DaySummary = days.reduce<DaySummary>(
    (acc, d) => ({
      added: acc.added + d.summary.added,
      went_live: acc.went_live + d.summary.went_live,
      expiring: acc.expiring + d.summary.expiring,
      removed: acc.removed + d.summary.removed,
    }),
    { added: 0, went_live: 0, expiring: 0, removed: 0 },
  );

  const start = days[0]?.date ?? "";
  const end = days.at(-1)?.date ?? start;

  const banner = `// AUTO-GENERATED by scripts/generate-changelog.ts — DO NOT EDIT.\n// Source of truth: data/changelog-diffs/<date>.json files.\n// Re-run with \`pnpm generate:changelog\`.\n`;

  const body = [
    banner,
    `import type { ChangeLog } from "./data";\n`,
    `export const GENERATED_CHANGE_LOG: ChangeLog = ${JSON.stringify(
      { days, weekRollup: { start, end, totals } },
      undefined,
      2,
    )};\n`,
  ].join("\n");

  writeFileSync(OUTPUT_FILE, body, "utf8");

  console.log(
    `Wrote ${days.length.toString()} day(s) ` +
      `${start === "" ? "(no diffs yet)" : `covering ${start} → ${end}`} → ${OUTPUT_FILE}`,
  );
};

main();
