import { createFromRoot, pdaNode, getAllPdas } from "codama";
import { rootNodeFromAnchor } from "@codama/nodes-from-anchor";
import { addPdasVisitor } from "@codama/visitors";
import {
  constantPdaSeedNodeFromString,
  variablePdaSeedNode,
  numberTypeNode,
  isNode,
} from "@codama/nodes";
import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const generatedDir = resolve(__dirname, "../generated/pda_helpers");

// ---------------------------------------------------------------------------
// Define PDA nodes for each program
// ---------------------------------------------------------------------------

const pythIdl = JSON.parse(
  readFileSync(resolve(__dirname, "idl/pyth_solana_receiver.json"), "utf8")
);
const pythCodama = createFromRoot(rootNodeFromAnchor(pythIdl));
pythCodama.update(
  addPdasVisitor({
    pythSolanaReceiver: [
      pdaNode({
        name: "config",
        seeds: [constantPdaSeedNodeFromString("utf8", "config")],
      }),
      pdaNode({
        name: "treasury",
        seeds: [
          constantPdaSeedNodeFromString("utf8", "treasury"),
          variablePdaSeedNode("treasuryId", numberTypeNode("u8")),
        ],
      }),
    ],
  })
);

const wormholeIdl = JSON.parse(
  readFileSync(
    resolve(__dirname, "idl/wormhole_core_bridge_solana.json"),
    "utf8"
  )
);
const wormholeCodama = createFromRoot(rootNodeFromAnchor(wormholeIdl));
wormholeCodama.update(
  addPdasVisitor({
    wormholeCoreBridgeSolana: [
      pdaNode({
        name: "guardianSet",
        seeds: [
          constantPdaSeedNodeFromString("utf8", "GuardianSet"),
          variablePdaSeedNode("index", numberTypeNode("u32")),
        ],
      }),
    ],
  })
);

// ---------------------------------------------------------------------------
// Generate Rust code from PDA definitions
// ---------------------------------------------------------------------------

function snakeCase(s) {
  return s.replace(/([a-z])([A-Z])/g, "$1_$2").toLowerCase();
}

function rustTypeForNumber(format) {
  return format; // u8, u16, u32, u64, etc. are already Rust types
}

function generateSeedExpr(seed) {
  if (isNode(seed, "constantPdaSeedNode")) {
    if (seed.value.kind === "stringValueNode") {
      return { expr: `b"${seed.value.string}"`, params: [] };
    }
    if (seed.value.kind === "bytesValueNode") {
      return { expr: `&[${seed.value.data.join(", ")}]`, params: [] };
    }
    throw new Error(`Unsupported constant seed value kind: ${seed.value.kind}`);
  }
  if (isNode(seed, "variablePdaSeedNode")) {
    const name = snakeCase(seed.name);
    const rustType = rustTypeForNumber(seed.type.format);
    if (rustType === "u8") {
      return { expr: `&[${name}]`, params: [{ name, type: rustType }] };
    }
    return {
      expr: `&${name}.to_be_bytes()`,
      params: [{ name, type: rustType }],
    };
  }
  throw new Error(`Unsupported seed kind: ${seed.kind}`);
}

function generatePdaFunction(pda) {
  const fnName = `find_${snakeCase(pda.name)}_pda`;
  const seedResults = pda.seeds.map(generateSeedExpr);
  const params = seedResults.flatMap((s) => s.params);
  const seedExprs = seedResults.map((s) => s.expr).join(", ");

  const paramList = [
    "program_id: &Pubkey",
    ...params.map((p) => `${p.name}: ${p.type}`),
  ].join(", ");

  return `/// Derive the \`${pda.name}\` PDA address.
pub fn ${fnName}(${paramList}) -> (Pubkey, u8) {
    Pubkey::find_program_address(&[${seedExprs}], program_id)
}`;
}

function generateModule(programName, pdas) {
  const modName = snakeCase(programName);
  const fns = pdas.map(generatePdaFunction).join("\n\n");
  return `pub mod ${modName} {
    use solana_sdk::pubkey::Pubkey;

${fns}
}`;
}

// ---------------------------------------------------------------------------
// Write generated Rust crate
// ---------------------------------------------------------------------------

const pythPdas = getAllPdas(pythCodama.getRoot());
const wormholePdas = getAllPdas(wormholeCodama.getRoot());

console.log(
  `Found ${pythPdas.length} pyth PDAs, ${wormholePdas.length} wormhole PDAs`
);

const modules = [
  generateModule("pyth_solana_receiver", pythPdas),
  generateModule("wormhole_core_bridge_solana", wormholePdas),
].join("\n\n");

const libRs = `//! Auto-generated PDA derivation helpers.
//!
//! This code was generated by the Codama-based generator in
//! \`generator/generate.mjs\`. Do not edit manually — re-run
//! \`npm run generate\` in the generator/ directory instead.

${modules}
`;

const cargoToml = `[package]
name = "pda-helpers"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
solana-sdk = "1.18"
`;

mkdirSync(resolve(generatedDir, "src"), { recursive: true });
writeFileSync(resolve(generatedDir, "src/lib.rs"), libRs);
writeFileSync(resolve(generatedDir, "Cargo.toml"), cargoToml);

console.log("Generated PDA helpers crate at generated/pda_helpers/");
console.log("  src/lib.rs");
console.log("  Cargo.toml");
