{
 "title": "Pyth Price Pusher Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "chain",
    "label": "Chain",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Configured Price Feeds", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Configured Price Feeds: ${chain}",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "repeat": "chain",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pyth_price_feeds_total{namespace=\"$chain\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Active Price Feeds", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Active Price Feeds: ${chain}",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "repeat": "chain",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pyth_price_last_published_time{namespace=\"$chain\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Time Since Last Update", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Time Since Last Update: ${chain}",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "repeat": "chain",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - pyth_price_last_published_time{namespace=\"$chain\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  { "title": "Price Feeds Lists", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Price Feeds List: ${chain}",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "repeat": "chain",
   "targets": [
    {
     "expr": "pyth_price_last_published_time{namespace=\"$chain\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "time() - pyth_price_last_published_time{namespace=\"$chain\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pyth_price_update_attempts_total{status=\"success\", namespace=\"$chain\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Updates Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Successful Updates: ${chain}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "repeat": "chain",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(pyth_price_update_attempts_total{status=\"success\", namespace=\"$chain\"}[$__range])",
     "legendFormat": "{{alias}} - Updates"
    }
   ]
  },
  { "title": "Update Conditions By Chain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Update Conditions: ${chain}",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "repeat": "chain",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (trigger) (increase(pyth_price_update_attempts_total{namespace=\"$chain\"}[$__range]))",
     "legendFormat": "{{trigger}}"
    }
   ]
  },
  { "title": "Wallet Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Wallet Balance: ${chain}",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 57 },
   "repeat": "chain",
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pyth_wallet_balance{namespace=\"$chain\"}",
     "legendFormat": "{{wallet_address}}"
    }
   ]
  },
  {
   "title": "Wallet Balance Over Time: ${chain}",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 63 },
   "repeat": "chain",
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "pyth_wallet_balance{namespace=\"$chain\"}",
     "legendFormat": "{{wallet_address}} ({{network}})"
    }
   ]
  },
  { "title": "Failed Updates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Failed Updates: ${chain}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "repeat": "chain",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(pyth_price_update_attempts_total{status=\"error\", namespace=\"$chain\"}[$__range])",
     "legendFormat": "{{alias}} - Errors"
    }
   ]
  },
  { "title": "Tx Hash", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Tx Hash: ${chain}",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "repeat": "chain",
   "targets": [
    {
     "expr": "{namespace=~\"$chain\"} | logfmt | json | msg =~ `.*(Price update successful|Transaction confirmed|Successfully updated price).*` | line_format `Tx Hash: {{.hash}}`"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "All Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "{namespace=~\"$chain\"} | logfmt"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "targets": [
    {
     "expr": "{namespace=~\"$chain\"} | logfmt | detected_level = `error`"
    }
   ]
  }
 ]
}