[package]
name = "pyth_lazer"
version = "0.0.0"
edition = "2024"

[dependencies.wormhole]
git = "https://github.com/wormhole-foundation/wormhole.git"
subdir = "sui/wormhole"
rev = "c5a2eabe0a48654fcb1d3c98537915c2fb671c80"
