BUN_INSTALL="/Users/gbescos/.bun" \
COMMAND_MODE="unix2003" \
CURSOR_EXTENSION_HOST_ROLE="agent-exec" \
CURSOR_LAYOUT="unifiedAgent" \
CURSOR_WORKSPACE_LABEL="pyth-crosschain" \
HOME="/Users/gbescos" \
HOMEBREW_CELLAR="/opt/homebrew/Cellar" \
HOMEBREW_PREFIX="/opt/homebrew" \
HOMEBREW_REPOSITORY="/opt/homebrew" \
INFOPATH="/opt/homebrew/share/info:/opt/homebrew/share/info:" \
LANG="C.UTF-8" \
LOGNAME="gbescos" \
MACH_PORT_RENDEZVOUS_PEER_VALDATION="0" \
MallocNanoZone="0" \
NVM_BIN="/Users/gbescos/.nvm/versions/node/v24.14.0/bin" \
NVM_CD_FLAGS="-q" \
NVM_DIR="/Users/gbescos/.nvm" \
NVM_INC="/Users/gbescos/.nvm/versions/node/v24.14.0/include/node" \
OLDPWD="/" \
OSLogRateLimit="64" \
PATH="/Users/gbescos/.bun/bin:/Users/gbescos/.krew/bin:/opt/homebrew/opt/gnu-tar/libexec/gnubin:/Users/gbescos/.local/share/solana/install/active_release/bin:/Users/gbescos/.nvm/versions/node/v24.14.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/pmk/env/global/bin:/Users/gbescos/.local/bin:/Applications/Cursor.app/Contents/Resources/app/resources/helpers:/Users/gbescos/.bun/bin:/Users/gbescos/.krew/bin:/Users/gbescos/Library/pnpm:/opt/homebrew/opt/gnu-tar/libexec/gnubin:/Users/gbescos/.local/share/solana/install/active_release/bin:/Users/gbescos/.nvm/versions/node/v24.14.0/bin:/Users/gbescos/.cargo/bin:/Users/gbescos/.foundry/bin" \
PNPM_HOME="/Users/gbescos/Library/pnpm" \
PWD="/Users/gbescos/Documents/repos/pyth-crosschain/target_chains/solana" \
SHELL="/bin/zsh" \
SHLVL="1" \
SSH_AUTH_SOCK="/private/tmp/com.apple.launchd.U0FstV9six/Listeners" \
TMPDIR="/var/folders/f0/1b_jt5dj1lv_dhrlml1j7_2m0000gn/T/" \
USER="gbescos" \
VSCODE_CODE_CACHE_PATH="/Users/gbescos/Library/Application Support/Cursor/CachedData/fce1e9ab7844f9ea35793da01e634aa7e50bce90" \
VSCODE_CRASH_REPORTER_PROCESS_TYPE="extensionHost" \
VSCODE_CWD="/" \
VSCODE_ESM_ENTRYPOINT="vs/workbench/api/node/extensionHostProcess" \
VSCODE_HANDLES_UNCAUGHT_ERRORS="true" \
VSCODE_IPC_HOOK="/Users/gbescos/Library/Application Support/Cursor/3.1.-main.sock" \
VSCODE_NLS_CONFIG="{"userLocale":"en-us","osLocale":"en-us","resolvedLanguage":"en","defaultMessagesFile":"/Applications/Cursor.app/Contents/Resources/app/out/nls.messages.json","locale":"en-us","availableLanguages":{}}" \
VSCODE_PID="1794" \
VSCODE_PROCESS_TITLE="extension-host (agent-exec) pyth-crosschain [6-32]" \
XPC_FLAGS="0x0" \
XPC_SERVICE_NAME="0" \
__CFBundleIdentifier="com.todesktop.230313mzl4w4u92" \
__CF_USER_TEXT_ENCODING="0x1F5:0x0:0x0" \
TERM="dumb" \
NO_COLOR="1" \
FORCE_COLOR="0" \
_ZO_DOCTOR="0" \
CURSOR_AGENT="1" \
_="/Users/gbescos/.local/share/solana/install/active_release/bin/cargo-build-sbf" \
CC="/Users/gbescos/.local/share/solana/install/releases/1.17.34/solana-release/bin/sdk/sbf/dependencies/platform-tools/llvm/bin/clang" \
AR="/Users/gbescos/.local/share/solana/install/releases/1.17.34/solana-release/bin/sdk/sbf/dependencies/platform-tools/llvm/bin/llvm-ar" \
OBJDUMP="/Users/gbescos/.local/share/solana/install/releases/1.17.34/solana-release/bin/sdk/sbf/dependencies/platform-tools/llvm/bin/llvm-objdump" \
OBJCOPY="/Users/gbescos/.local/share/solana/install/releases/1.17.34/solana-release/bin/sdk/sbf/dependencies/platform-tools/llvm/bin/llvm-objcopy" \
CARGO_TARGET_SBF_SOLANA_SOLANA_RUSTFLAGS="  -Zremap-cwd-prefix=" \
cargo+solana build --release --target sbf-solana-solana --verbose
