export const DEFAULT_TREASURY_ID = 0;
export const DEFAULT_REDUCED_GUARDIAN_SET_SIZE = 5;

export const VERIFY_ENCODED_VAA_COMPUTE_BUDGET = 400000;
export const POST_UPDATE_ATOMIC_COMPUTE_BUDGET = 400000;
export const POST_UPDATE_COMPUTE_BUDGET = 200000;
